[build]
builder = "nixpacks"
# cache-bust: 2026-04-27

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
